image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - master  # ветка git

build: off  # будем использовать свой скрипт сборки

install:


build_script:
  - chmod u+x gradlew
  - gradle wrapper --debug
  - ls -a
  - ./gradlew test  --info  # запускаем тест, флаг --info позволяет выводить больше информации
